[profile.default]
src = "src"
out = "out"
libs = ["lib", "lib/forge-std", "lib/openzeppelin-contracts"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
localA = "http://127.0.0.1:8545"
localB = "http://127.0.0.1:8546"

[profile.localA]
chain_id = 1337
rpc_url = "${rpc_endpoints.localA}"

[profile.localB]
chain_id = 31337
rpc_url = "${rpc_endpoints.localB}"


